---
abstract: 'Quickly and easily create secure passwords'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  List::MoreUtils: 0
  Module::Build: 0.3601
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Genpass
requires:
  Carp: 0
  Config::Any: 0
  File::HomeDir: 0
  List::AllUtils: 0
  Mouse: 0
  MouseX::ConfigFromFile: 0
  MouseX::Getopt: 0
  Path::Class: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/xsawyerx/app-genpass
version: 2.00
